
%============================================================================
% Library Facts
%============================================================================

%----------------------------------------------------------------------------
% Library: lib.so
%----------------------------------------------------------------------------
abi_typelocation("lib.so","_ZSt4cout","Import","Integer8","var").
abi_typelocation("lib.so","_ZSt4cout","Import","Integer8","var").
abi_typelocation("lib.so","_ZSt4cout","Import","Integer8","var").
abi_typelocation("lib.so","_ZSt4cout","Import","Integer8","var").
abi_typelocation("lib.so","_ZSt4cout","Import","Integer8","var").
abi_typelocation("lib.so","_ZSt4cout","Import","Integer32","var").
abi_typelocation("lib.so","_ZSt4cout","Import","Integer64","var").
abi_typelocation("lib.so","_ZSt4cout","Import","Integer8","var").
abi_typelocation("lib.so","_ZSt4cout","Import","Integer32","var").
abi_typelocation("lib.so","_ZSt4cout","Import","Integer32","var").
abi_typelocation("lib.so","_ZSt4cout","Import","Integer32","var").
abi_typelocation("lib.so","_ZSt4cout","Import","Integer8","var").
abi_typelocation("lib.so","_ZSt4cout","Import","Integer32","var").
abi_typelocation("lib.so","_ZSt4cout","Import","Integer32","var").
abi_typelocation("lib.so","_ZSt4cout","Import","Integer8","var").
abi_typelocation("lib.so","_ZNSt15__exception_ptr13exception_ptrD4Ev","Import","Integer32","%rsi").
abi_typelocation("lib.so","_ZNKSt15__exception_ptr13exception_ptrcvbEv","Export","Integer8","%rax").
abi_typelocation("lib.so","_ZNSt11char_traitsIcE2eqERKcS2_","Export","Integer8","%rax").
abi_typelocation("lib.so","_ZNSt11char_traitsIcE2ltERKcS2_","Export","Integer8","%rax").
abi_typelocation("lib.so","_ZNSt11char_traitsIcE7compareEPKcS2_m","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","_ZNSt11char_traitsIcE7compareEPKcS2_m","Export","Integer32","%rax").
abi_typelocation("lib.so","_ZNSt11char_traitsIcE6lengthEPKc","Export","Integer64","(%rax)").
abi_typelocation("lib.so","_ZNSt11char_traitsIcE4findEPKcmRS1_","Import","Integer64","(%rsi)").
abi_typelocation("lib.so","_ZNSt11char_traitsIcE4moveEPcPKcm","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","_ZNSt11char_traitsIcE4copyEPcPKcm","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","_ZNSt11char_traitsIcE6assignEPcmc","Import","Integer64","(%rsi)").
abi_typelocation("lib.so","_ZNSt11char_traitsIcE6assignEPcmc","Import","Integer8","(%rdx)").
abi_typelocation("lib.so","_ZNSt11char_traitsIcE12to_char_typeERKi","Export","Integer8","(%rax)").
abi_typelocation("lib.so","_ZNSt11char_traitsIcE11to_int_typeERKc","Export","Integer32","(%rax)").
abi_typelocation("lib.so","_ZNSt11char_traitsIcE11eq_int_typeERKiS2_","Export","Integer8","%rax").
abi_typelocation("lib.so","_ZNSt11char_traitsIcE3eofEv","Export","Integer32","(%rax)").
abi_typelocation("lib.so","_ZNSt11char_traitsIcE7not_eofERKi","Export","Integer32","(%rax)").
abi_typelocation("lib.so","_ZNSt8ios_base4InitD4Ev","Import","Integer32","%rsi").
abi_typelocation("lib.so","_ZNSolsEi","Import","Integer32","%rsi").
abi_typelocation("lib.so","_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_c","Import","Integer8","%rsi").
abi_typelocation("lib.so","btowc","Import","Integer32","%rdi").
abi_typelocation("lib.so","btowc","Export","Integer32","(%rax)").
abi_typelocation("lib.so","fgetwc","Export","Integer32","(%rax)").
abi_typelocation("lib.so","fgetws","Import","Integer32","%rsi").
abi_typelocation("lib.so","fputwc","Import","Integer32","%rdi").
abi_typelocation("lib.so","fputwc","Export","Integer32","(%rax)").
abi_typelocation("lib.so","fputws","Export","Integer32","%rax").
abi_typelocation("lib.so","fwide","Import","Integer32","%rsi").
abi_typelocation("lib.so","fwide","Export","Integer32","%rax").
abi_typelocation("lib.so","fwprintf","Export","Integer32","%rax").
abi_typelocation("lib.so","__isoc99_fwscanf","Export","Integer32","%rax").
abi_typelocation("lib.so","getwc","Export","Integer32","(%rax)").
abi_typelocation("lib.so","getwchar","Export","Integer32","(%rax)").
abi_typelocation("lib.so","mbrlen","Import","Integer64","(%rsi)").
abi_typelocation("lib.so","mbrlen","Export","Integer64","(%rax)").
abi_typelocation("lib.so","mbrtowc","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","mbrtowc","Export","Integer64","(%rax)").
abi_typelocation("lib.so","mbsinit","Export","Integer32","%rax").
abi_typelocation("lib.so","mbsrtowcs","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","mbsrtowcs","Export","Integer64","(%rax)").
abi_typelocation("lib.so","putwc","Import","Integer32","%rdi").
abi_typelocation("lib.so","putwc","Export","Integer32","(%rax)").
abi_typelocation("lib.so","putwchar","Import","Integer32","%rdi").
abi_typelocation("lib.so","putwchar","Export","Integer32","(%rax)").
abi_typelocation("lib.so","swprintf","Import","Integer64","(%rsi)").
abi_typelocation("lib.so","swprintf","Export","Integer32","%rax").
abi_typelocation("lib.so","__isoc99_swscanf","Export","Integer32","%rax").
abi_typelocation("lib.so","ungetwc","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","ungetwc","Export","Integer32","(%rax)").
abi_typelocation("lib.so","vfwprintf","Export","Integer32","%rax").
abi_typelocation("lib.so","__isoc99_vfwscanf","Export","Integer32","%rax").
abi_typelocation("lib.so","vswprintf","Import","Integer64","(%rsi)").
abi_typelocation("lib.so","vswprintf","Export","Integer32","%rax").
abi_typelocation("lib.so","__isoc99_vswscanf","Export","Integer32","%rax").
abi_typelocation("lib.so","vwprintf","Export","Integer32","%rax").
abi_typelocation("lib.so","__isoc99_vwscanf","Export","Integer32","%rax").
abi_typelocation("lib.so","wcrtomb","Import","Integer32","%rsi").
abi_typelocation("lib.so","wcrtomb","Export","Integer64","(%rax)").
abi_typelocation("lib.so","wcscmp","Export","Integer32","%rax").
abi_typelocation("lib.so","wcscoll","Export","Integer32","%rax").
abi_typelocation("lib.so","wcscspn","Export","Integer64","(%rax)").
abi_typelocation("lib.so","wcsftime","Import","Integer64","(%rsi)").
abi_typelocation("lib.so","wcsftime","Export","Integer64","(%rax)").
abi_typelocation("lib.so","wcslen","Export","Integer64","(%rax)").
abi_typelocation("lib.so","wcsncat","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","wcsncmp","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","wcsncmp","Export","Integer32","%rax").
abi_typelocation("lib.so","wcsncpy","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","wcsrtombs","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","wcsrtombs","Export","Integer64","(%rax)").
abi_typelocation("lib.so","wcsspn","Export","Integer64","(%rax)").
abi_typelocation("lib.so","wcstod","Export","Float64","%xmm0").
abi_typelocation("lib.so","wcstof","Export","Float32","%xmm0").
abi_typelocation("lib.so","wcstol","Import","Integer32","%rdx").
abi_typelocation("lib.so","wcstol","Export","Integer64","%rax").
abi_typelocation("lib.so","wcstoul","Import","Integer32","%rdx").
abi_typelocation("lib.so","wcstoul","Export","Integer64","%rax").
abi_typelocation("lib.so","wcsxfrm","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","wcsxfrm","Export","Integer64","(%rax)").
abi_typelocation("lib.so","wctob","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","wctob","Export","Integer32","%rax").
abi_typelocation("lib.so","wmemcmp","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","wmemcmp","Export","Integer32","%rax").
abi_typelocation("lib.so","wmemcpy","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","wmemmove","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","wmemset","Import","Integer32","%rsi").
abi_typelocation("lib.so","wmemset","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","wprintf","Export","Integer32","%rax").
abi_typelocation("lib.so","__isoc99_wscanf","Export","Integer32","%rax").
abi_typelocation("lib.so","wcschr","Import","Integer32","%rsi").
abi_typelocation("lib.so","wcschr","Import","Integer32","%rsi").
abi_typelocation("lib.so","wcsrchr","Import","Integer32","%rsi").
abi_typelocation("lib.so","wcsrchr","Import","Integer32","%rsi").
abi_typelocation("lib.so","wmemchr","Import","Integer32","%rsi").
abi_typelocation("lib.so","wmemchr","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","wmemchr","Import","Integer32","%rsi").
abi_typelocation("lib.so","wmemchr","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","_ZN9__gnu_cxx3divExx","Import","Integer64","%rdi").
abi_typelocation("lib.so","_ZN9__gnu_cxx3divExx","Import","Integer64","%rsi").
abi_typelocation("lib.so","_ZN9__gnu_cxx3divExx","Import","Integer64","()").
abi_typelocation("lib.so","_ZN9__gnu_cxx3divExx","Import","Integer64","(()+8)").
abi_typelocation("lib.so","wcstold","Export","Float128","%st0").
abi_typelocation("lib.so","wcstoll","Import","Integer32","%rdx").
abi_typelocation("lib.so","wcstoll","Export","Integer64","%rax").
abi_typelocation("lib.so","wcstoull","Import","Integer32","%rdx").
abi_typelocation("lib.so","wcstoull","Export","Integer64","%rax").
abi_typelocation("lib.so","setlocale","Import","Integer32","%rdi").
abi_typelocation("lib.so","atexit","Export","Integer32","%rax").
abi_typelocation("lib.so","at_quick_exit","Export","Integer32","%rax").
abi_typelocation("lib.so","atof","Export","Float64","%xmm0").
abi_typelocation("lib.so","atoi","Export","Integer32","%rax").
abi_typelocation("lib.so","atol","Export","Integer64","%rax").
abi_typelocation("lib.so","bsearch","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","bsearch","Import","Integer64","(%rcx)").
abi_typelocation("lib.so","bsearch","Import","Pointer64","(%r8)").
abi_typelocation("lib.so","div","Import","Integer32","%rdi").
abi_typelocation("lib.so","div","Import","Integer32","%rsi").
abi_typelocation("lib.so","div","Import","Integer32","()").
abi_typelocation("lib.so","div","Import","Integer32","(()+4)").
abi_typelocation("lib.so","ldiv","Import","Integer64","%rdi").
abi_typelocation("lib.so","ldiv","Import","Integer64","%rsi").
abi_typelocation("lib.so","ldiv","Import","Integer64","()").
abi_typelocation("lib.so","ldiv","Import","Integer64","(()+8)").
abi_typelocation("lib.so","mblen","Import","Integer64","(%rsi)").
abi_typelocation("lib.so","mblen","Export","Integer32","%rax").
abi_typelocation("lib.so","mbstowcs","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","mbstowcs","Export","Integer64","(%rax)").
abi_typelocation("lib.so","mbtowc","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","mbtowc","Export","Integer32","%rax").
abi_typelocation("lib.so","qsort","Import","Integer64","(%rsi)").
abi_typelocation("lib.so","qsort","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","qsort","Import","Pointer64","(%rcx)").
abi_typelocation("lib.so","quick_exit","Import","Integer32","%rdi").
abi_typelocation("lib.so","rand","Export","Integer32","%rax").
abi_typelocation("lib.so","srand","Import","Integer32","%rdi").
abi_typelocation("lib.so","strtod","Export","Float64","%xmm0").
abi_typelocation("lib.so","strtol","Import","Integer32","%rdx").
abi_typelocation("lib.so","strtol","Export","Integer64","%rax").
abi_typelocation("lib.so","strtoul","Import","Integer32","%rdx").
abi_typelocation("lib.so","strtoul","Export","Integer64","%rax").
abi_typelocation("lib.so","system","Export","Integer32","%rax").
abi_typelocation("lib.so","wcstombs","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","wcstombs","Export","Integer64","(%rax)").
abi_typelocation("lib.so","wctomb","Import","Integer32","%rsi").
abi_typelocation("lib.so","wctomb","Export","Integer32","%rax").
abi_typelocation("lib.so","lldiv","Import","Integer64","%rdi").
abi_typelocation("lib.so","lldiv","Import","Integer64","%rsi").
abi_typelocation("lib.so","lldiv","Import","Integer64","()").
abi_typelocation("lib.so","lldiv","Import","Integer64","(()+8)").
abi_typelocation("lib.so","atoll","Export","Integer64","%rax").
abi_typelocation("lib.so","strtoll","Import","Integer32","%rdx").
abi_typelocation("lib.so","strtoll","Export","Integer64","%rax").
abi_typelocation("lib.so","strtoull","Import","Integer32","%rdx").
abi_typelocation("lib.so","strtoull","Export","Integer64","%rax").
abi_typelocation("lib.so","strtof","Export","Float32","%xmm0").
abi_typelocation("lib.so","strtold","Export","Float128","%st0").
abi_typelocation("lib.so","fclose","Export","Integer32","%rax").
abi_typelocation("lib.so","feof","Export","Integer32","%rax").
abi_typelocation("lib.so","ferror","Export","Integer32","%rax").
abi_typelocation("lib.so","fflush","Export","Integer32","%rax").
abi_typelocation("lib.so","fgetc","Export","Integer32","%rax").
abi_typelocation("lib.so","fgetpos","Export","Integer32","%rax").
abi_typelocation("lib.so","fgets","Import","Integer32","%rsi").
abi_typelocation("lib.so","fread","Import","Integer64","(%rsi)").
abi_typelocation("lib.so","fread","Import","Integer64","(%rdx)").
abi_typelocation("lib.so","fread","Export","Integer64","(%rax)").
abi_typelocation("lib.so","fseek","Import","Integer64","%rsi").
abi_typelocation("lib.so","fseek","Import","Integer32","%rdx").
abi_typelocation("lib.so","fseek","Export","Integer32","%rax").
abi_typelocation("lib.so","fsetpos","Export","Integer32","%rax").
abi_typelocation("lib.so","ftell","Export","Integer64","%rax").
abi_typelocation("lib.so","getc","Export","Integer32","%rax").
abi_typelocation("lib.so","getchar","Export","Integer32","%rax").
abi_typelocation("lib.so","remove","Export","Integer32","%rax").
abi_typelocation("lib.so","rename","Export","Integer32","%rax").
abi_typelocation("lib.so","setvbuf","Import","Integer32","%rdx").
abi_typelocation("lib.so","setvbuf","Import","Integer64","(%rcx)").
abi_typelocation("lib.so","setvbuf","Export","Integer32","%rax").
abi_typelocation("lib.so","ungetc","Import","Integer32","%rdi").
abi_typelocation("lib.so","ungetc","Export","Integer32","%rax").
abi_typelocation("lib.so","iswctype","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","iswctype","Import","Integer64","(%rsi)").
abi_typelocation("lib.so","iswctype","Export","Integer32","%rax").
abi_typelocation("lib.so","towctrans","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","towctrans","Import","Pointer64","(%rsi)").
abi_typelocation("lib.so","towctrans","Export","Integer32","(%rax)").
abi_typelocation("lib.so","wctrans","Export","Pointer64","(%rax)").
abi_typelocation("lib.so","wctype","Export","Integer64","(%rax)").
abi_typelocation("lib.so","main","Export","Integer32","%rax").
abi_typelocation("lib.so","_Z6invokeiiPFiiiE","Import","Integer32","%rdi").
abi_typelocation("lib.so","_Z6invokeiiPFiiiE","Import","Integer32","%rsi").
abi_typelocation("lib.so","_Z6invokeiiPFiiiE","Export","Integer32","%rax").
abi_typelocation("lib.so","_Z8multiplyii","Import","Integer32","%rdi").
abi_typelocation("lib.so","_Z8multiplyii","Import","Integer32","%rsi").
abi_typelocation("lib.so","_Z8multiplyii","Export","Integer32","%rax").
abi_typelocation("lib.so","_Z3addii","Import","Integer32","%rdi").
abi_typelocation("lib.so","_Z3addii","Import","Integer32","%rsi").
abi_typelocation("lib.so","_Z3addii","Export","Integer32","%rax").
