
%============================================================================
% Library Facts
%============================================================================

%----------------------------------------------------------------------------
% Library: lib.so
%----------------------------------------------------------------------------
abi_typelocation("lib.so","_ZSt4cout","Import","Integer8","var").
abi_typelocation("lib.so","_ZSt4cout","Export","Integer8","var").
abi_typelocation("lib.so","_ZSt4cout","Export","Integer8","var").
abi_typelocation("lib.so","_ZSt4cout","Export","Integer8","var").
abi_typelocation("lib.so","_ZSt4cout","Export","Integer32","var").
abi_typelocation("lib.so","_ZSt4cout","Export","Integer32","var").
abi_typelocation("lib.so","_ZSt4cout","Export","Integer8","var").
abi_typelocation("lib.so","_ZSt4cout","Export","Integer8","var").
abi_typelocation("lib.so","_ZNSt15__exception_ptr13exception_ptrD4Ev","Import","Integer32","%rsi").
abi_typelocation("lib.so","_ZNKSt15__exception_ptr13exception_ptrcvbEv","Export","Integer8","%rax").
abi_typelocation("lib.so","_ZNSt11char_traitsIcE2eqERKcS2_","Export","Integer8","%rax").
abi_typelocation("lib.so","_ZNSt11char_traitsIcE2ltERKcS2_","Export","Integer8","%rax").
abi_typelocation("lib.so","_ZNSt11char_traitsIcE7compareEPKcS2_m","Export","Integer32","%rax").
abi_typelocation("lib.so","_ZNSt11char_traitsIcE11eq_int_typeERKiS2_","Export","Integer8","%rax").
abi_typelocation("lib.so","_ZNSt8ios_base4InitD4Ev","Import","Integer32","%rsi").
abi_typelocation("lib.so","_ZNSolsEi","Import","Integer8","(%rdi)").
abi_typelocation("lib.so","_ZNSolsEi","Export","Integer8","(%rdi)").
abi_typelocation("lib.so","_ZNSolsEi","Export","Integer8","(%rdi)").
abi_typelocation("lib.so","_ZNSolsEi","Export","Integer8","(%rdi)").
abi_typelocation("lib.so","_ZNSolsEi","Export","Integer32","(%rdi)").
abi_typelocation("lib.so","_ZNSolsEi","Export","Integer32","(%rdi)").
abi_typelocation("lib.so","_ZNSolsEi","Export","Integer8","(%rdi)").
abi_typelocation("lib.so","_ZNSolsEi","Export","Integer8","(%rdi)").
abi_typelocation("lib.so","_ZNSolsEi","Import","Integer32","%rsi").
abi_typelocation("lib.so","_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_c","Import","Integer8","%rdi").
abi_typelocation("lib.so","btowc","Import","Integer32","%rdi").
abi_typelocation("lib.so","fgetws","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","fgetws","Import","Integer32","%rsi").
abi_typelocation("lib.so","fgetws","Export","Integer32","(%rax)").
abi_typelocation("lib.so","fputwc","Import","Integer32","%rdi").
abi_typelocation("lib.so","fputws","Export","Integer32","%rax").
abi_typelocation("lib.so","fwide","Import","Integer32","%rsi").
abi_typelocation("lib.so","fwide","Export","Integer32","%rax").
abi_typelocation("lib.so","fwprintf","Export","Integer32","%rax").
abi_typelocation("lib.so","mbrtowc","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","mbsinit","Export","Integer32","%rax").
abi_typelocation("lib.so","mbsrtowcs","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","putwc","Import","Integer32","%rdi").
abi_typelocation("lib.so","putwchar","Import","Integer32","%rdi").
abi_typelocation("lib.so","swprintf","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","swprintf","Export","Integer32","%rax").
abi_typelocation("lib.so","vfwprintf","Export","Integer32","(%rdx)").
abi_typelocation("lib.so","vfwprintf","Export","Integer32","((%rdx)+4)").
abi_typelocation("lib.so","vfwprintf","Export","Integer32","%rax").
abi_typelocation("lib.so","vswprintf","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","vswprintf","Export","Integer32","(%rdx)").
abi_typelocation("lib.so","vswprintf","Export","Integer32","((%rdx)+4)").
abi_typelocation("lib.so","vswprintf","Export","Integer32","%rax").
abi_typelocation("lib.so","vwprintf","Export","Integer32","(%rsi)").
abi_typelocation("lib.so","vwprintf","Export","Integer32","((%rsi)+4)").
abi_typelocation("lib.so","vwprintf","Export","Integer32","%rax").
abi_typelocation("lib.so","wcrtomb","Import","Integer8","(%rdi)").
abi_typelocation("lib.so","wcrtomb","Import","Integer32","%rsi").
abi_typelocation("lib.so","wcscat","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","wcscat","Export","Integer32","(%rax)").
abi_typelocation("lib.so","wcscmp","Export","Integer32","%rax").
abi_typelocation("lib.so","wcscoll","Export","Integer32","%rax").
abi_typelocation("lib.so","wcscpy","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","wcscpy","Export","Integer32","(%rax)").
abi_typelocation("lib.so","wcsftime","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","wcsncat","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","wcsncat","Export","Integer32","(%rax)").
abi_typelocation("lib.so","wcsncmp","Export","Integer32","%rax").
abi_typelocation("lib.so","wcsncpy","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","wcsncpy","Export","Integer32","(%rax)").
abi_typelocation("lib.so","wcsrtombs","Import","Integer8","(%rdi)").
abi_typelocation("lib.so","wcstod","Import","Integer32","((%rsi))").
abi_typelocation("lib.so","wcstod","Export","Float64","%xmm0").
abi_typelocation("lib.so","wcstof","Import","Integer32","((%rsi))").
abi_typelocation("lib.so","wcstof","Export","Float32","%xmm0").
abi_typelocation("lib.so","wcstok","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","wcstok","Import","Integer32","((%rdx))").
abi_typelocation("lib.so","wcstok","Export","Integer32","(%rax)").
abi_typelocation("lib.so","wcstol","Import","Integer32","((%rsi))").
abi_typelocation("lib.so","wcstol","Import","Integer32","%rdx").
abi_typelocation("lib.so","wcstol","Export","Integer64","%rax").
abi_typelocation("lib.so","wcstoul","Import","Integer32","((%rsi))").
abi_typelocation("lib.so","wcstoul","Import","Integer32","%rdx").
abi_typelocation("lib.so","wcstoul","Export","Integer64","%rax").
abi_typelocation("lib.so","wcsxfrm","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","wctob","Export","Integer32","%rax").
abi_typelocation("lib.so","wmemcmp","Export","Integer32","%rax").
abi_typelocation("lib.so","wmemcpy","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","wmemcpy","Export","Integer32","(%rax)").
abi_typelocation("lib.so","wmemmove","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","wmemmove","Export","Integer32","(%rax)").
abi_typelocation("lib.so","wmemset","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","wmemset","Import","Integer32","%rsi").
abi_typelocation("lib.so","wmemset","Export","Integer32","(%rax)").
abi_typelocation("lib.so","wprintf","Export","Integer32","%rax").
abi_typelocation("lib.so","wcschr","Import","Integer32","%rsi").
abi_typelocation("lib.so","wcschr","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","wcschr","Import","Integer32","%rsi").
abi_typelocation("lib.so","wcschr","Export","Integer32","(%rax)").
abi_typelocation("lib.so","wcspbrk","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","wcspbrk","Export","Integer32","(%rax)").
abi_typelocation("lib.so","wcsrchr","Import","Integer32","%rsi").
abi_typelocation("lib.so","wcsrchr","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","wcsrchr","Import","Integer32","%rsi").
abi_typelocation("lib.so","wcsrchr","Export","Integer32","(%rax)").
abi_typelocation("lib.so","wcsstr","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","wcsstr","Export","Integer32","(%rax)").
abi_typelocation("lib.so","wmemchr","Import","Integer32","%rsi").
abi_typelocation("lib.so","wmemchr","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","wmemchr","Import","Integer32","%rsi").
abi_typelocation("lib.so","wmemchr","Export","Integer32","(%rax)").
abi_typelocation("lib.so","_ZN9__gnu_cxx3divExx","Import","Integer64","%rdi").
abi_typelocation("lib.so","_ZN9__gnu_cxx3divExx","Import","Integer64","%rsi").
abi_typelocation("lib.so","wcstold","Import","Integer32","((%rsi))").
abi_typelocation("lib.so","wcstold","Export","Float128","%st0").
abi_typelocation("lib.so","wcstoll","Import","Integer32","((%rsi))").
abi_typelocation("lib.so","wcstoll","Import","Integer32","%rdx").
abi_typelocation("lib.so","wcstoll","Export","Integer64","%rax").
abi_typelocation("lib.so","wcstoull","Import","Integer32","((%rsi))").
abi_typelocation("lib.so","wcstoull","Import","Integer32","%rdx").
abi_typelocation("lib.so","wcstoull","Export","Integer64","%rax").
abi_typelocation("lib.so","setlocale","Import","Integer32","%rdi").
abi_typelocation("lib.so","setlocale","Export","Integer8","(%rax)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax))").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+8)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+16)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+24)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+32)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+40)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+48)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+56)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+64)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+72)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+80)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+81)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+82)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+83)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+84)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+85)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+86)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+87)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+88)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+89)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+90)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+91)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+92)").
abi_typelocation("lib.so","localeconv","Export","Integer8","((%rax)+93)").
abi_typelocation("lib.so","atexit","Export","Integer32","%rax").
abi_typelocation("lib.so","at_quick_exit","Export","Integer32","%rax").
abi_typelocation("lib.so","atof","Export","Float64","%xmm0").
abi_typelocation("lib.so","atoi","Export","Integer32","%rax").
abi_typelocation("lib.so","atol","Export","Integer64","%rax").
abi_typelocation("lib.so","div","Import","Integer32","%rdi").
abi_typelocation("lib.so","div","Import","Integer32","%rsi").
abi_typelocation("lib.so","getenv","Export","Integer8","(%rax)").
abi_typelocation("lib.so","ldiv","Import","Integer64","%rdi").
abi_typelocation("lib.so","ldiv","Import","Integer64","%rsi").
abi_typelocation("lib.so","mblen","Export","Integer32","%rax").
abi_typelocation("lib.so","mbstowcs","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","mbtowc","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","mbtowc","Export","Integer32","%rax").
abi_typelocation("lib.so","quick_exit","Import","Integer32","%rdi").
abi_typelocation("lib.so","rand","Export","Integer32","%rax").
abi_typelocation("lib.so","srand","Import","Integer32","%rdi").
abi_typelocation("lib.so","strtod","Import","Integer8","((%rsi))").
abi_typelocation("lib.so","strtod","Export","Float64","%xmm0").
abi_typelocation("lib.so","strtol","Import","Integer8","((%rsi))").
abi_typelocation("lib.so","strtol","Import","Integer32","%rdx").
abi_typelocation("lib.so","strtol","Export","Integer64","%rax").
abi_typelocation("lib.so","strtoul","Import","Integer8","((%rsi))").
abi_typelocation("lib.so","strtoul","Import","Integer32","%rdx").
abi_typelocation("lib.so","strtoul","Export","Integer64","%rax").
abi_typelocation("lib.so","system","Export","Integer32","%rax").
abi_typelocation("lib.so","wcstombs","Import","Integer8","(%rdi)").
abi_typelocation("lib.so","wctomb","Import","Integer8","(%rdi)").
abi_typelocation("lib.so","wctomb","Import","Integer32","%rsi").
abi_typelocation("lib.so","wctomb","Export","Integer32","%rax").
abi_typelocation("lib.so","lldiv","Import","Integer64","%rdi").
abi_typelocation("lib.so","lldiv","Import","Integer64","%rsi").
abi_typelocation("lib.so","atoll","Export","Integer64","%rax").
abi_typelocation("lib.so","strtoll","Import","Integer8","((%rsi))").
abi_typelocation("lib.so","strtoll","Import","Integer32","%rdx").
abi_typelocation("lib.so","strtoll","Export","Integer64","%rax").
abi_typelocation("lib.so","strtoull","Import","Integer8","((%rsi))").
abi_typelocation("lib.so","strtoull","Import","Integer32","%rdx").
abi_typelocation("lib.so","strtoull","Export","Integer64","%rax").
abi_typelocation("lib.so","strtof","Import","Integer8","((%rsi))").
abi_typelocation("lib.so","strtof","Export","Float32","%xmm0").
abi_typelocation("lib.so","strtold","Import","Integer8","((%rsi))").
abi_typelocation("lib.so","strtold","Export","Float128","%st0").
abi_typelocation("lib.so","fclose","Export","Integer32","%rax").
abi_typelocation("lib.so","feof","Export","Integer32","%rax").
abi_typelocation("lib.so","ferror","Export","Integer32","%rax").
abi_typelocation("lib.so","fflush","Export","Integer32","%rax").
abi_typelocation("lib.so","fgetc","Export","Integer32","%rax").
abi_typelocation("lib.so","fgetpos","Export","Integer32","%rax").
abi_typelocation("lib.so","fgets","Import","Integer8","(%rdi)").
abi_typelocation("lib.so","fgets","Import","Integer32","%rsi").
abi_typelocation("lib.so","fgets","Export","Integer8","(%rax)").
abi_typelocation("lib.so","fseek","Import","Integer64","%rsi").
abi_typelocation("lib.so","fseek","Import","Integer32","%rdx").
abi_typelocation("lib.so","fseek","Export","Integer32","%rax").
abi_typelocation("lib.so","fsetpos","Export","Integer32","%rax").
abi_typelocation("lib.so","ftell","Export","Integer64","%rax").
abi_typelocation("lib.so","getc","Export","Integer32","%rax").
abi_typelocation("lib.so","getchar","Export","Integer32","%rax").
abi_typelocation("lib.so","remove","Export","Integer32","%rax").
abi_typelocation("lib.so","rename","Export","Integer32","%rax").
abi_typelocation("lib.so","setbuf","Import","Integer8","(%rsi)").
abi_typelocation("lib.so","setvbuf","Import","Integer8","(%rsi)").
abi_typelocation("lib.so","setvbuf","Import","Integer32","%rdx").
abi_typelocation("lib.so","setvbuf","Export","Integer32","%rax").
abi_typelocation("lib.so","tmpnam","Import","Integer8","(%rdi)").
abi_typelocation("lib.so","tmpnam","Export","Integer8","(%rax)").
abi_typelocation("lib.so","ungetc","Import","Integer32","%rdi").
abi_typelocation("lib.so","ungetc","Export","Integer32","%rax").
abi_typelocation("lib.so","iswctype","Export","Integer32","%rax").
abi_typelocation("lib.so","main","Export","Integer32","%rax").
abi_typelocation("lib.so","_Z6invokeiiPFiiiE","Import","Integer32","%rdi").
abi_typelocation("lib.so","_Z6invokeiiPFiiiE","Import","Integer32","%rsi").
abi_typelocation("lib.so","_Z6invokeiiPFiiiE","Export","Integer32","%rax").
abi_typelocation("lib.so","_Z8multiplyii","Import","Integer32","%rdi").
abi_typelocation("lib.so","_Z8multiplyii","Import","Integer32","%rsi").
abi_typelocation("lib.so","_Z8multiplyii","Export","Integer32","%rax").
abi_typelocation("lib.so","_Z3addii","Import","Integer32","%rdi").
abi_typelocation("lib.so","_Z3addii","Import","Integer32","%rsi").
abi_typelocation("lib.so","_Z3addii","Export","Integer32","%rax").
