
%============================================================================
% Library Facts
%============================================================================

%----------------------------------------------------------------------------
% Library: lib.so
%----------------------------------------------------------------------------
abi_typelocation("lib.so","_Z11struct_funciP3Foo","Import","Integer32","%rdi").
abi_typelocation("lib.so","_Z11struct_funciP3Foo","Import","Integer32","(%rsi)").
abi_typelocation("lib.so","_Z11struct_funciP3Foo","Import","Float64","((%rsi)+8)").
abi_typelocation("lib.so","_Z11struct_funciP3Foo","Import","Integer8","((%rsi)+16)").
abi_typelocation("lib.so","_Z11struct_funciP3Foo","Export","Integer32","%rax").
abi_typelocation("lib.so","_Z3barP10AnotherFoo","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","_Z3barP10AnotherFoo","Import","Float64","((%rdi)+8)").
abi_typelocation("lib.so","_Z3barP10AnotherFoo","Import","Integer8","((%rdi)+16)").
abi_typelocation("lib.so","_Z3barP10AnotherFoo","Import","Integer32","((%rdi)+24)").
abi_typelocation("lib.so","_Z3barP10AnotherFoo","Import","Float64","(((%rdi)+24)+8)").
abi_typelocation("lib.so","_Z3barP10AnotherFoo","Import","Integer8","(((%rdi)+24)+16)").
abi_typelocation("lib.so","_Z3barP10AnotherFoo","Import","Float64","(+8)").
abi_typelocation("lib.so","_Z3barP10AnotherFoo","Import","Integer8","(+16)").
abi_typelocation("lib.so","_Z3barP10AnotherFoo","Import","Integer32","(+24)").
abi_typelocation("lib.so","_Z3barP10AnotherFoo","Import","Float64","((+24)+8)").
abi_typelocation("lib.so","_Z3barP10AnotherFoo","Import","Integer8","((+24)+16)").
abi_typelocation("lib.so","_Z3foo10AnotherFoo","Export","Integer32","%rdi").
abi_typelocation("lib.so","_Z3foo10AnotherFoo","Export","Float64","(%xmm0+8)").
abi_typelocation("lib.so","_Z3foo10AnotherFoo","Export","Integer8","(%rsi+16)").
abi_typelocation("lib.so","_Z3foo10AnotherFoo","Import","Integer32","(%rdx+24)").
abi_typelocation("lib.so","_Z3foo10AnotherFoo","Import","Float64","((%rdx+24)+8)").
abi_typelocation("lib.so","_Z3foo10AnotherFoo","Import","Integer8","((%rdx+24)+16)").
abi_typelocation("lib.so","_Z3foo10AnotherFoo","Export","Integer32","%rax").
abi_typelocation("lib.so","_Z3fooP3Foo","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","_Z3fooP3Foo","Import","Float64","((%rdi)+8)").
abi_typelocation("lib.so","_Z3fooP3Foo","Import","Integer8","((%rdi)+16)").
abi_typelocation("lib.so","_Z3buxP3Bux","Import","Integer32","(((%rdi)))").
abi_typelocation("lib.so","_Z3buxP3Bux","Import","Float64","((((%rdi)))+8)").
abi_typelocation("lib.so","_Z3buxP3Bux","Import","Integer8","((((%rdi)))+16)").
abi_typelocation("lib.so","_Z3bux3Bux","Import","Integer32","((%rdi))").
abi_typelocation("lib.so","_Z3bux3Bux","Import","Float64","(((%rdi))+8)").
abi_typelocation("lib.so","_Z3bux3Bux","Import","Integer8","(((%rdi))+16)").
abi_typelocation("lib.so","_Z3baxP3Bax","Import","Integer32","((%rdi))").
abi_typelocation("lib.so","_Z3baxP3Bax","Import","Float64","(((%rdi))+8)").
abi_typelocation("lib.so","_Z3baxP3Bax","Import","Integer8","(((%rdi))+16)").
abi_typelocation("lib.so","_Z3bax3Bax","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","_Z3bax3Bax","Import","Float64","((%rdi)+8)").
abi_typelocation("lib.so","_Z3bax3Bax","Import","Integer8","((%rdi)+16)").
abi_typelocation("lib.so","_Z3bazP3Baz","Import","Integer32","((%rdi))").
abi_typelocation("lib.so","_Z3bazP3Baz","Import","Float64","(((%rdi))+8)").
abi_typelocation("lib.so","_Z3bazP3Baz","Import","Integer8","(((%rdi))+16)").
abi_typelocation("lib.so","_Z3baz3Baz","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","_Z3baz3Baz","Import","Float64","((%rdi)+8)").
abi_typelocation("lib.so","_Z3baz3Baz","Import","Integer8","((%rdi)+16)").
abi_typelocation("lib.so","_Z3barP3Bar","Import","Integer32","(%rdi)").
abi_typelocation("lib.so","_Z3barP3Bar","Import","Float64","((%rdi)+8)").
abi_typelocation("lib.so","_Z3barP3Bar","Import","Integer8","((%rdi)+16)").
abi_typelocation("lib.so","_Z3bar3Bar","Import","Float64","(+8)").
abi_typelocation("lib.so","_Z3bar3Bar","Import","Integer8","(+16)").
abi_typelocation("lib.so","_Z3foo3Foo","Export","Integer32","%rdi").
abi_typelocation("lib.so","_Z3foo3Foo","Export","Float64","(%xmm0+8)").
abi_typelocation("lib.so","_Z3foo3Foo","Export","Integer8","(%rsi+16)").
