
%============================================================================
% Library Facts
%============================================================================

%----------------------------------------------------------------------------
% Library: example
%----------------------------------------------------------------------------
abi_typelocation("example","main","Export","Integer32","%rax").
abi_typelocation("example","test_void","Export","Void","none").
abi_typelocation("example","test_ptr_ptr_uint_least64_t","Import","TypeDef64","(((%rdi)))").
abi_typelocation("example","test_ptr_uint_least64_t","Import","TypeDef64","((%rdi))").
abi_typelocation("example","test_uint_least64_t","Import","TypeDef64","()").
abi_typelocation("example","test_ptr_ptr_uint_least32_t","Import","TypeDef32","(((%rdi)))").
abi_typelocation("example","test_ptr_uint_least32_t","Import","TypeDef32","((%rdi))").
abi_typelocation("example","test_uint_least32_t","Import","TypeDef32","()").
abi_typelocation("example","test_ptr_ptr_uint_least16_t","Import","TypeDef16","(((%rdi)))").
abi_typelocation("example","test_ptr_uint_least16_t","Import","TypeDef16","((%rdi))").
abi_typelocation("example","test_uint_least16_t","Import","TypeDef16","()").
abi_typelocation("example","test_ptr_ptr_uint_least8_t","Import","TypeDef8","(((%rdi)))").
abi_typelocation("example","test_ptr_uint_least8_t","Import","TypeDef8","((%rdi))").
abi_typelocation("example","test_uint_least8_t","Import","TypeDef8","()").
abi_typelocation("example","test_ptr_ptr_uint_fast64_t","Import","Integer64","(((%rdi)))").
abi_typelocation("example","test_ptr_uint_fast64_t","Import","Integer64","((%rdi))").
abi_typelocation("example","test_uint_fast64_t","Import","Integer64","(%rdi)").
abi_typelocation("example","test_ptr_ptr_uint_fast32_t","Import","Integer64","(((%rdi)))").
abi_typelocation("example","test_ptr_uint_fast32_t","Import","Integer64","((%rdi))").
abi_typelocation("example","test_uint_fast32_t","Import","Integer64","(%rdi)").
abi_typelocation("example","test_ptr_ptr_uint_fast16_t","Import","Integer64","(((%rdi)))").
abi_typelocation("example","test_ptr_uint_fast16_t","Import","Integer64","((%rdi))").
abi_typelocation("example","test_uint_fast16_t","Import","Integer64","(%rdi)").
abi_typelocation("example","test_ptr_ptr_uint_fast8_t","Import","Integer8","(((%rdi)))").
abi_typelocation("example","test_ptr_uint_fast8_t","Import","Integer8","((%rdi))").
abi_typelocation("example","test_uint_fast8_t","Import","Integer8","(%rdi)").
abi_typelocation("example","test_ptr_ptr_uint64_t","Import","TypeDef64","(((%rdi)))").
abi_typelocation("example","test_ptr_uint64_t","Import","TypeDef64","((%rdi))").
abi_typelocation("example","test_uint64_t","Import","TypeDef64","()").
abi_typelocation("example","test_ptr_ptr_uint32_t","Import","TypeDef32","(((%rdi)))").
abi_typelocation("example","test_ptr_uint32_t","Import","TypeDef32","((%rdi))").
abi_typelocation("example","test_uint32_t","Import","TypeDef32","()").
abi_typelocation("example","test_ptr_ptr_uint16_t","Import","TypeDef16","(((%rdi)))").
abi_typelocation("example","test_ptr_uint16_t","Import","TypeDef16","((%rdi))").
abi_typelocation("example","test_uint16_t","Import","TypeDef16","()").
abi_typelocation("example","test_ptr_ptr_uint8_t","Import","TypeDef8","(((%rdi)))").
abi_typelocation("example","test_ptr_uint8_t","Import","TypeDef8","((%rdi))").
abi_typelocation("example","test_uint8_t","Import","TypeDef8","()").
abi_typelocation("example","test_ptr_ptr_int_least64_t","Import","TypeDef64","(((%rdi)))").
abi_typelocation("example","test_ptr_int_least64_t","Import","TypeDef64","((%rdi))").
abi_typelocation("example","test_int_least64_t","Import","TypeDef64","()").
abi_typelocation("example","test_ptr_ptr_int_least32_t","Import","TypeDef32","(((%rdi)))").
abi_typelocation("example","test_ptr_int_least32_t","Import","TypeDef32","((%rdi))").
abi_typelocation("example","test_int_least32_t","Import","TypeDef32","()").
abi_typelocation("example","test_ptr_ptr_int_least16_t","Import","TypeDef16","(((%rdi)))").
abi_typelocation("example","test_ptr_int_least16_t","Import","TypeDef16","((%rdi))").
abi_typelocation("example","test_int_least16_t","Import","TypeDef16","()").
abi_typelocation("example","test_ptr_ptr_int_least8_t","Import","TypeDef8","(((%rdi)))").
abi_typelocation("example","test_ptr_int_least8_t","Import","TypeDef8","((%rdi))").
abi_typelocation("example","test_int_least8_t","Import","TypeDef8","()").
abi_typelocation("example","test_ptr_ptr_int_fast64_t","Import","Integer64","(((%rdi)))").
abi_typelocation("example","test_ptr_int_fast64_t","Import","Integer64","((%rdi))").
abi_typelocation("example","test_int_fast64_t","Import","Integer64","(%rdi)").
abi_typelocation("example","test_ptr_ptr_int_fast32_t","Import","Integer64","(((%rdi)))").
abi_typelocation("example","test_ptr_int_fast32_t","Import","Integer64","((%rdi))").
abi_typelocation("example","test_int_fast32_t","Import","Integer64","(%rdi)").
abi_typelocation("example","test_ptr_ptr_int_fast16_t","Import","Integer64","(((%rdi)))").
abi_typelocation("example","test_ptr_int_fast16_t","Import","Integer64","((%rdi))").
abi_typelocation("example","test_int_fast16_t","Import","Integer64","(%rdi)").
abi_typelocation("example","test_ptr_ptr_int_fast8_t","Import","Integer8","(((%rdi)))").
abi_typelocation("example","test_ptr_int_fast8_t","Import","Integer8","((%rdi))").
abi_typelocation("example","test_int_fast8_t","Import","Integer8","(%rdi)").
abi_typelocation("example","test_ptr_ptr_int64_t","Import","TypeDef64","(((%rdi)))").
abi_typelocation("example","test_ptr_int64_t","Import","TypeDef64","((%rdi))").
abi_typelocation("example","test_int64_t","Import","TypeDef64","()").
abi_typelocation("example","test_ptr_ptr_int32_t","Import","TypeDef32","(((%rdi)))").
abi_typelocation("example","test_ptr_int32_t","Import","TypeDef32","((%rdi))").
abi_typelocation("example","test_int32_t","Import","TypeDef32","()").
abi_typelocation("example","test_ptr_ptr_int16_t","Import","TypeDef16","(((%rdi)))").
abi_typelocation("example","test_ptr_int16_t","Import","TypeDef16","((%rdi))").
abi_typelocation("example","test_int16_t","Import","TypeDef16","()").
abi_typelocation("example","test_ptr_ptr_int8_t","Import","TypeDef8","(((%rdi)))").
abi_typelocation("example","test_ptr_int8_t","Import","TypeDef8","((%rdi))").
abi_typelocation("example","test_int8_t","Import","TypeDef8","()").
abi_typelocation("example","test_ptr_ptr_uintptr_t","Import","Integer64","(((%rdi)))").
abi_typelocation("example","test_ptr_uintptr_t","Import","Integer64","((%rdi))").
abi_typelocation("example","test_uintptr_t","Import","Integer64","(%rdi)").
abi_typelocation("example","test_ptr_ptr_intptr_t","Import","Integer64","(((%rdi)))").
abi_typelocation("example","test_ptr_intptr_t","Import","Integer64","((%rdi))").
abi_typelocation("example","test_intptr_t","Import","Integer64","(%rdi)").
abi_typelocation("example","test_ptr_ptr_uintmax_t","Import","TypeDef64","(((%rdi)))").
abi_typelocation("example","test_ptr_uintmax_t","Import","TypeDef64","((%rdi))").
abi_typelocation("example","test_uintmax_t","Import","TypeDef64","()").
abi_typelocation("example","test_ptr_ptr_intmax_t","Import","TypeDef64","(((%rdi)))").
abi_typelocation("example","test_ptr_intmax_t","Import","TypeDef64","((%rdi))").
abi_typelocation("example","test_intmax_t","Import","TypeDef64","()").
abi_typelocation("example","test_ptr_ptr_size_t","Import","Integer64","(((%rdi)))").
abi_typelocation("example","test_ptr_size_t","Import","Integer64","((%rdi))").
abi_typelocation("example","test_size_t","Import","Integer64","(%rdi)").
abi_typelocation("example","test_ptr_ptr_char32_t","Import","Integer32","((%rdi))").
abi_typelocation("example","test_ptr_char32_t","Import","Integer32","(%rdi)").
abi_typelocation("example","test_char32_t","Import","Integer32","%rdi").
abi_typelocation("example","test_ptr_ptr_char16_t","Import","Integer16","((%rdi))").
abi_typelocation("example","test_ptr_char16_t","Import","Integer16","(%rdi)").
abi_typelocation("example","test_char16_t","Import","Integer16","%rdi").
abi_typelocation("example","test_ptr_ptr_wchar_t","Import","Integer32","((%rdi))").
abi_typelocation("example","test_ptr_wchar_t","Import","Integer32","(%rdi)").
abi_typelocation("example","test_wchar_t","Import","Integer32","%rdi").
abi_typelocation("example","test_ptr_ptr_long_double__Complex","Import","ComplexFloat256","((%rdi))").
abi_typelocation("example","test_ptr_long_double__Complex","Import","ComplexFloat256","(%rdi)").
abi_typelocation("example","test_long_double__Complex","Import","ComplexFloat256","framebase+8").
abi_typelocation("example","test_ptr_ptr_double__Complex","Import","ComplexFloat128","((%rdi))").
abi_typelocation("example","test_ptr_double__Complex","Import","ComplexFloat128","(%rdi)").
abi_typelocation("example","test_double__Complex","Import","ComplexFloat128","framebase+8").
abi_typelocation("example","test_ptr_ptr_float__Complex","Import","ComplexFloat64","((%rdi))").
abi_typelocation("example","test_ptr_float__Complex","Import","ComplexFloat64","(%rdi)").
abi_typelocation("example","test_float__Complex","Import","ComplexFloat64","framebase+8").
abi_typelocation("example","test_ptr_ptr_long_double","Import","Float128","((%rdi))").
abi_typelocation("example","test_ptr_long_double","Import","Float128","(%rdi)").
abi_typelocation("example","test_long_double","Import","Float128","framebase+8").
abi_typelocation("example","test_ptr_ptr_double","Import","Float64","((%rdi))").
abi_typelocation("example","test_ptr_double","Import","Float64","(%rdi)").
abi_typelocation("example","test_double","Import","Float64","%xmm0").
abi_typelocation("example","test_ptr_ptr_float","Import","Float32","((%rdi))").
abi_typelocation("example","test_ptr_float","Import","Float32","(%rdi)").
abi_typelocation("example","test_float","Import","Float32","%xmm0").
abi_typelocation("example","test_ptr_ptr_unsigned_long_long","Import","Integer64","((%rdi))").
abi_typelocation("example","test_ptr_unsigned_long_long","Import","Integer64","(%rdi)").
abi_typelocation("example","test_unsigned_long_long","Import","Integer64","%rdi").
abi_typelocation("example","test_ptr_ptr_unsigned_long","Import","Integer64","((%rdi))").
abi_typelocation("example","test_ptr_unsigned_long","Import","Integer64","(%rdi)").
abi_typelocation("example","test_unsigned_long","Import","Integer64","%rdi").
abi_typelocation("example","test_ptr_ptr_unsigned_int","Import","Integer32","((%rdi))").
abi_typelocation("example","test_ptr_unsigned_int","Import","Integer32","(%rdi)").
abi_typelocation("example","test_unsigned_int","Import","Integer32","%rdi").
abi_typelocation("example","test_ptr_ptr_unsigned_short","Import","Integer16","((%rdi))").
abi_typelocation("example","test_ptr_unsigned_short","Import","Integer16","(%rdi)").
abi_typelocation("example","test_unsigned_short","Import","Integer16","%rdi").
abi_typelocation("example","test_ptr_ptr_unsigned_char","Import","Integer8","((%rdi))").
abi_typelocation("example","test_ptr_unsigned_char","Import","Integer8","(%rdi)").
abi_typelocation("example","test_unsigned_char","Import","Integer8","%rdi").
abi_typelocation("example","test_ptr_ptr_unsigned","Import","Integer32","((%rdi))").
abi_typelocation("example","test_ptr_unsigned","Import","Integer32","(%rdi)").
abi_typelocation("example","test_unsigned","Import","Integer32","%rdi").
abi_typelocation("example","test_ptr_ptr_signed_long_long","Import","Integer64","((%rdi))").
abi_typelocation("example","test_ptr_signed_long_long","Import","Integer64","(%rdi)").
abi_typelocation("example","test_signed_long_long","Import","Integer64","%rdi").
abi_typelocation("example","test_ptr_ptr_signed_long","Import","Integer64","((%rdi))").
abi_typelocation("example","test_ptr_signed_long","Import","Integer64","(%rdi)").
abi_typelocation("example","test_signed_long","Import","Integer64","%rdi").
abi_typelocation("example","test_ptr_ptr_signed_int","Import","Integer32","((%rdi))").
abi_typelocation("example","test_ptr_signed_int","Import","Integer32","(%rdi)").
abi_typelocation("example","test_signed_int","Import","Integer32","%rdi").
abi_typelocation("example","test_ptr_ptr_signed_short","Import","Integer16","((%rdi))").
abi_typelocation("example","test_ptr_signed_short","Import","Integer16","(%rdi)").
abi_typelocation("example","test_signed_short","Import","Integer16","%rdi").
abi_typelocation("example","test_ptr_ptr_signed_char","Import","Integer8","((%rdi))").
abi_typelocation("example","test_ptr_signed_char","Import","Integer8","(%rdi)").
abi_typelocation("example","test_signed_char","Import","Integer8","%rdi").
abi_typelocation("example","test_ptr_ptr_signed","Import","Integer32","((%rdi))").
abi_typelocation("example","test_ptr_signed","Import","Integer32","(%rdi)").
abi_typelocation("example","test_signed","Import","Integer32","%rdi").
abi_typelocation("example","test_ptr_ptr_long_long","Import","Integer64","((%rdi))").
abi_typelocation("example","test_ptr_long_long","Import","Integer64","(%rdi)").
abi_typelocation("example","test_long_long","Import","Integer64","%rdi").
abi_typelocation("example","test_ptr_ptr_long","Import","Integer64","((%rdi))").
abi_typelocation("example","test_ptr_long","Import","Integer64","(%rdi)").
abi_typelocation("example","test_long","Import","Integer64","%rdi").
abi_typelocation("example","test_ptr_ptr_int","Import","Integer32","((%rdi))").
abi_typelocation("example","test_ptr_int","Import","Integer32","(%rdi)").
abi_typelocation("example","test_int","Import","Integer32","%rdi").
abi_typelocation("example","test_ptr_ptr_short","Import","Integer16","((%rdi))").
abi_typelocation("example","test_ptr_short","Import","Integer16","(%rdi)").
abi_typelocation("example","test_short","Import","Integer16","%rdi").
abi_typelocation("example","test_ptr_ptr_char","Import","Integer8","((%rdi))").
abi_typelocation("example","test_ptr_char","Import","Integer8","(%rdi)").
abi_typelocation("example","test_char","Import","Integer8","%rdi").
abi_typelocation("example","test_ptr_ptr_bool","Import","Integer8","((%rdi))").
abi_typelocation("example","test_ptr_bool","Import","Integer8","(%rdi)").
abi_typelocation("example","test_bool","Import","Integer8","%rdi").
